
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JFLEX_Y_CUP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 30;
  public static final int Y = 50;
  public static final int CABIERTO = 42;
  public static final int PABIERTO = 37;
  public static final int CHAR = 55;
  public static final int POR = 34;
  public static final int MAI = 49;
  public static final int PUNTOYCOMA = 29;
  public static final int RET = 24;
  public static final int LLABIERTO = 39;
  public static final int GBAJO = 35;
  public static final int O = 51;
  public static final int CASE = 25;
  public static final int PRIVATE = 3;
  public static final int INT = 10;
  public static final int COMENT = 57;
  public static final int SWI = 22;
  public static final int FOR = 19;
  public static final int IGUAL = 31;
  public static final int CARACTER = 13;
  public static final int DIVIDIDO = 36;
  public static final int IGUALDAD = 46;
  public static final int IF = 16;
  public static final int THIS = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int DECIMAL = 14;
  public static final int CLASE = 7;
  public static final int COMILLA = 41;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int IFEL = 17;
  public static final int MENOS = 33;
  public static final int MENOR = 44;
  public static final int MAYOR = 45;
  public static final int WHI = 20;
  public static final int IMPORT = 2;
  public static final int ENT = 53;
  public static final int NEGAR = 52;
  public static final int EL = 18;
  public static final int CCERRADO = 43;
  public static final int PCERRADO = 38;
  public static final int PROTECTED = 5;
  public static final int PUNTO = 27;
  public static final int DESIGUALDAD = 47;
  public static final int FINAL = 6;
  public static final int BOL = 56;
  public static final int LLCERRADO = 40;
  public static final int MEI = 48;
  public static final int PUBLIC = 4;
  public static final int STRING = 12;
  public static final int BRE = 23;
  public static final int DEF = 26;
  public static final int TEXTO = 59;
  public static final int STEX = 58;
  public static final int DEC = 54;
  public static final int OBJETOS = 15;
  public static final int DO = 21;
  public static final int MAS = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IMPORT",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "FINAL",
  "CLASE",
  "THIS",
  "NEW",
  "INT",
  "BOOLEAN",
  "STRING",
  "CARACTER",
  "DECIMAL",
  "OBJETOS",
  "IF",
  "IFEL",
  "EL",
  "FOR",
  "WHI",
  "DO",
  "SWI",
  "BRE",
  "RET",
  "CASE",
  "DEF",
  "PUNTO",
  "COMA",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "GBAJO",
  "DIVIDIDO",
  "PABIERTO",
  "PCERRADO",
  "LLABIERTO",
  "LLCERRADO",
  "COMILLA",
  "CABIERTO",
  "CCERRADO",
  "MENOR",
  "MAYOR",
  "IGUALDAD",
  "DESIGUALDAD",
  "MEI",
  "MAI",
  "Y",
  "O",
  "NEGAR",
  "ENT",
  "DEC",
  "CHAR",
  "BOL",
  "COMENT",
  "STEX",
  "TEXTO"
  };
}

